version: '3'

services:
  app:
    image: svelte_dev:17-alpine
    build: .
    user: "node:node"
    container_name: svelte_dev
    environment:
      NODE_ENV: "development"
    volumes:
      - ./:/usr/src/app
    working_dir: "/usr/src/app/svelte-app/"
    ports:
      - "4200:4200"
    tty: true
